apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
{{- if .Values.prometheus.addAnnotations }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "9090"
{{- end }}
      namespace: {{ .Values.namespace }}
    spec:
      containers:
      - name: kafqa
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        command: {{ .Values.image.command }}
        env:
          - name: KAFKA_CLUSTER
            value: {{ .Values.kafka.cluster | quote }}
          - name: PRODUCER_KAFKA_BROKERS
            value: {{ .Values.producer.kafkaBrokers | quote }}
          - name: PRODUCER_TOTAL_MESSAGES
            value: {{ .Values.producer.totalMessages | quote }}
          - name: PRODUCER_CONCURRENCY
            value: {{ .Values.producer.concurrency | quote }}
          - name: PRODUCER_WORKER_DELAY_MS
            value: {{ .Values.producer.workerDelayMs | quote }}
          - name: PRODUCER_ENABLED
            value: {{ .Values.producer.enabled | quote }}
          - name: PRODUCER_ACKS
            value: {{ .Values.acks | quote }}
          - name: APP_ENVIRONMENT
            value: {{ .Values.environment }}
          - name: APP_DURATION_MS
            value: {{ .Values.appDurationMs | quote }}
          - name:  KAFKA_TOPIC
            value: {{ .Values.kafka.topic | quote }}
          - name: CONSUMER_ENABLED
            value: {{ .Values.consumer.enabled | quote }}
          - name: CONSUMER_CONCURRENCY
            value: {{ .Values.consumer.concurrency | quote }}
          - name: CONSUMER_KAFKA_BROKERS
            value: {{ .Values.consumer.kafkaBrokers | quote }}
          - name: CONSUMER_GROUP_ID
            value: {{ .Values.consumer.groupId }}
          - name: CONSUMER_POLL_TIMEOUT_MS
            value: {{ .Values.consumer.pollTimeoutMs | quote }}
          - name: CONSUMER_ENABLE_AUTO_COMMIT
            value: {{ .Values.consumer.enableAutoCommit | quote }}
          - name: PROMETHEUS_ENABLED
            value: {{ .Values.prometheus.enabled | quote }}
          - name: PROMETHEUS_PORT
            value: {{ .Values.prometheus.port | quote }}
          - name: STATSD_ENABLED
            value: {{ .Values.stats.enabled | quote }}
          - name: STATSD_HOST
            value: {{ .Values.stats.host | quote }}
          - name: STATSD_PORT
            value: {{ .Values.stats.port | quote }}
          - name: LIBRD_ENABLED
            value: {{ .Values.librd.enabled | quote }}
          - name: LIBRD_QUEUE_BUFFERING_MAX_MESSAGE
            value: {{ .Values.librd.queueMaxSize | quote }}
          - name: LIBRD_BATCH_NUM_MESSAGES
            value: {{ .Values.librd.batchSize | quote }}
          - name: LIBRD_QUEUED_MIN_MESSAGES
            value: {{ .Values.librd.queuedMinMessages | quote }}
          - name: LIBRD_REQUEST_REQUIRED_ACKS
            value: {{ .Values.acks | quote }}
          - name: LIBRD_STATISTICS_INTERVAL_MS
            value: {{ .Values.librd.statsIntervalMs | quote }}
          - name: JAEGER_DISABLED
            value: {{ .Values.opentracing.jaegerDisabled | quote | default true }}
          - name: JAEGER_REPORT_LOG_SPANS
            value: {{ .Values.opentracing.jaegerReportLogSpans | quote | default false }}
          - name: JAEGER_AGENT_HOST
            value: {{ .Values.opentracing.jaegerAgentHost | default "localhost" | quote }}
          - name: JAEGER_AGENT_PORT
            value: {{ .Values.opentracing.jaegerAgentPort | default 6831 | quote }}
{{- if .Values.consumer.protoMessage }}
          - name: PROTO_PARSER_ENABLED
            value: "true"
          - name: PROTO_PARSER_MESSAGE_NAME
            value: {{ .Values.consumer.protoMessage.Name | quote  }}
          - name: PROTO_PARSER_FILE_PATH
            value: {{ .Values.consumer.protoMessage.FilePath | quote }}
          - name: PROTO_PARSER_TIMESTAMP_INDEX
            value: {{ .Values.consumer.protoMessage.TimestampIndex | quote }}
{{- end }}
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: DEPLOYMENT
            value: {{ include "kafqa.fullname" . }}
{{- if .Values.consumer.protoMessage }}
        volumeMounts:
        - name: kafqa-proto-config
          mountPath: {{ default "/usr/src" .Values.consumer.mountPath | quote }}
{{- end }}
        resources: 
{{ toYaml .Values.resources.kafqa | indent 12 }}
{{- if not .Values.opentracing.jaegerDisabled}}
      - name: jaeger-agent
        image: jaegertracing/jaeger-agent:latest
        imagePullPolicy: IfNotPresent
        env:
          - name: REPORTER_GRPC_HOST_PORT
            value: {{ .Values.opentracing.collectorHost }}:{{ .Values.opentracing.collectorPort }}
        ports:
        - containerPort: 5775
          protocol: UDP
        - containerPort: 6831
          protocol: UDP
        - containerPort: 6832
          protocol: UDP
        - containerPort: 5778
          protocol: TCP
        resources:
          limits:
            cpu: 1000m
            memory: 256Mi
          requests:
            cpu: 500m
            memory: 64Mi
{{- end }}
      - name: telegrafd
        image: {{ .Values.telegraf.image.repository }}:{{ .Values.telegraf.image.tag }}
        volumeMounts:
        - name: telegraf-conf
          mountPath: /etc/telegraf
        resources: 
{{ toYaml .Values.resources.telegraf | indent 12 }}       
      volumes:
      - name: telegraf-conf
        configMap:
          name: {{ .Release.Name }}-telegrafd
{{- if .Values.consumer.protoMessage }}
      - name: kafqa-proto-config
        configMap:
          name: {{ .Values.configmap }}
{{- end }}
