{{- if .Values.multiClusterSupport }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "albatross.fullname" . }}-secret
  namespace: {{ .Values.deployment.metadata.namespace }}
  labels:
    app: {{ include "albatross.fullname" . | indent 4}}
data:
  {{- range .Values.secrets }}
  {{ .key }}: {{ .value }}
  {{- end }}
{{- end }}
