apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/load-balancer-type: Internal
  name: {{ include "albatross.fullname" . }}
  namespace: {{ .Values.deployment.metadata.namespace }}
  labels:
{{ include "albatross.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.ip }}
  loadBalancerIP: {{ .Values.service.ip }}
  {{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.appPort }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "albatross.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
