{{- if .Values.createStorageClass }}
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  annotations:
  labels:
    addonmanager.kubernetes.io/mode: EnsureExists
    kubernetes.io/cluster-service: "true"
  name: {{ .Values.pvc.storageClassName }}
parameters:
  type: pd-standard
  fstype: ext4
provisioner: kubernetes.io/gce-pd
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
{{- end }}
