# Default values for albatross
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deployment:
  metadata:
    namespace: helming
  spec:
    replicas: 2
  livenessProbe:
    enabled: true
    initialDelaySeconds: 3
    timeoutSeconds: 3
image:
  repository: gojektech/albatross
  tag: latest
  pullPolicy: Always
containers:
  command: ["./albatross"]
pvc:
  accessMode: ReadWriteOnce
  storageRequest: 200Mi
  storageClassName: custom-storage-01

# Value of secrets should be base64 encoded
secrets:
  - key: secret-key-0
    value: c2VjcmV0LWtleS12YWx1ZS0wCg==
  - key: data
    value: ZGF0YS12YWx1ZQo=
config:
  name: "albatross-config"
  home_dir: /helm/config
  repositories:
    - name: gojektech-incubator
      url: https://gojek.github.io/charts/incubator/
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
useStaticRepository: true
multiClusterSupport: false
# for first time run enable this or set storage class to default
createStorageClass: false

# caData and clientCert & key data should be base 64 encoded
kubeconfig:
  clusters:
    - name: cluster-integration
      server: https://10.20.0.1
      caData: Y2FDbGllbnRDZXJ0QmFzZTY0RW5jb2RlZAo=
    - name: cluster-test
      server: https://10.20.0.2
      caData: Y2FDbGllbnRDZXJ0QmFzZTY0RW5jb2RlZAo=
  contexts:
    - cluster: cluster-integration
      namespace: helming
      user: albatross
      name: cluster-integration-ctx
  users:
    - name: albatross
      clientCertData: Y2xpZW50Q2VydGlmaWNhdGVCYXNlNjRFbmNvZGVkCg==
      clientKeyData: Y2xpZW50Q2VydGlmaWNhdGVCYXNlNjRFbmNvZGVkCg==
service:
  type: LoadBalancer
  port: 80

appPort: 8080

show_documentation: false
